options:
  logs_bucket: 'gs://test-build-01'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/eng-cogency-430509-q8/hello-world-app', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/eng-cogency-430509-q8/hello-world-app']
